image:
  file: .devcontainer/Dockerfile
github:
  prebuilds:
    pullRequestsFromForks: false
    addBadge: true
    addCheck: true
    pullRequests: false
    addLabel: true
    branches: false
additionalRepositories:
  - url: https://github.com/OFVp-Project/OpenSSH.git
tasks:
  - command: npm install
  - command: docker run -d -p 27017:27017/tcp mongo
ports:
  - name: OFVp API
    description: API to maneger Users and auth
    port: 3000
    visibility: public
    onOpen: notify
  - port: 5000
    onOpen: ignore
  - port: 27017
    onOpen: ignore
vscode:
  extensions:
    - "akamud.vscode-theme-onedark"
    - "formulahendry.auto-rename-tag"
    - "hookyqr.beautify"
    - "aaron-bond.better-comments"
    - "dbaeumer.vscode-eslint"
    - "oderwat.indent-rainbow"
    - "eg2.vscode-npm-script"
    - "christian-kohler.npm-intellisense"
    - "ionutvmi.path-autocomplete"
    - "christian-kohler.path-intellisense"
    - "esbenp.prettier-vscode"
    - "rangav.vscode-thunder-client"
    - "vscode-icons-team.vscode-icons"
    - "redhat.vscode-yaml"
    - "eamodio.gitlens"
    - "mongodb.mongodb-vscode"
    - "ms-azuretools.vscode-docker"