version: "3.9"
volumes:
  data_api:
  data_ssh:
  MongoOFVp:
networks:
  ofvp_network:
services:
  ofvp_mongodb:
    container_name: ofvp_mongodb
    restart: on-failure
    image: mongo
    volumes:
      - MongoOFVp:/data/db
    networks:
      - "ofvp_network"
    environment:
      - PUID=1000
      - PGID=1000
    entrypoint:
    - "mongod"
    - "--bind_ip_all"
    - "--quiet"
    - "--logpath"
    - "/dev/null"
    
  ofvp_openssh:
    container_name: ofvp_openssh
    restart: on-failure
    image: ghcr.io/ofvp-project/openssh:nightly
    networks:
      - "ofvp_network"
    environment:
      DAEMON_HOST: "http://ofvp_daemon_maneger:5000"
      DAEMON_PASSWORD: "dev"
      DAEMON_USER: "dev"
    ports:
      - 2222:22/tcp
    volumes:
      - data_ssh:/data
  ofvp_webproxy:
    image: ghcr.io/ofvp-project/webproxy:nightly
    container_name: ofvp_webproxy
    restart: on-failure
    depends_on:
      - ofvp_server
    networks:
      - "ofvp_network"
    ports:
      - 80:80/tcp
    command:
      - "--ssh"
      - "ofvp_openssh:22"

  ofvp_daemon_maneger:
    container_name: ofvp_daemon_maneger
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/ofvp-project/deamonmaneger:local
    depends_on:
      - ofvp_mongodb
      - ofvp_openssh
    networks:
      - "ofvp_network"
    environment:
      NODE_ENV: "development"
      MongoDB_URL: "mongodb://ofvp_mongodb:27017"
      COOKIE_SECRET: "dev"
      PASSWORD_ENCRYPT: "dev"
      DAEMON_PASSWORD: "dev"
      DAEMON_USER: "dev"
      OPENSSH_ENDPOINT_HOST: "ofvp_openssh"
      OPENSSH_ENDPOINT_PORT: "3002"
      OPENSSH_PORT: "2222"
    ports:
      - 3000:3000/tcp
    volumes:
      - data_api:/data
