version: "3.9"
networks:
  defaultOfvpNetwork:
volumes:
  mongoStorage:
  sshStorage:

services:
  mongodb:
    image: mongo
    restart: always
    command: "--bind_ip_all --port 27017 --noauth --quiet --logpath /dev/null"
    networks: [defaultOfvpNetwork]
    volumes: [mongoStorage:/data/db]

  maneger:
    build: ./
    ports: [3000:3000/tcp]
    networks: [defaultOfvpNetwork]
    depends_on: [mongodb]
    environment:
      NODE_ENV: "development"
      MONGO_URL: "mongodb://mongodb:27017/ofvp"
      PASSWORD_SECERET: "dev"
      COOKIE_SECRET: "dev"

  wireguard:
    image: ghcr.io/ofvp-project/wireguard:next
    restart: always
    depends_on: [maneger]
    networks: [defaultOfvpNetwork]
    volumes: [/lib/modules/:/lib/modules/:ro]
    ports: [51820:51820/udp]
    privileged: true
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
      net.ipv4.ip_forward: 1
    environment:
      DAEMON_HOST: "http://maneger:5000"
      DAEMON_USERNAME: ""
      DAEMON_PASSWORD: ""

  ssh:
    image: ghcr.io/ofvp-project/ssh-server:next
    restart: always
    depends_on: [maneger]
    networks: [defaultOfvpNetwork]
    ports: [2222:22/tcp]
    volumes: [sshStorage:/data]
    environment:
      NODE_ENV: "development"
      MONGO_URL: "mongodb://mongodb:27017/ofvp"
      PASSWORD_SECERET: "dev"

  webproxy:
    image: ghcr.io/ofvp-project/webproxy:latest
    restart: always
    depends_on: [ssh]
    networks: [defaultOfvpNetwork]
    ports: [8080:80/tcp]
    command: "-l 1 --ssh ssh:22"