version: "3.9"
volumes:
  data_api:
  MongoOFVp:
networks:
  ofvp_network:
    # enable_ipv6: true
services:
  ofvp_mongodb:
    container_name: ofvp_mongodb
    restart: on-failure
    image: mongo
    volumes:
      - MongoOFVp:/data/db
    networks:
      - "ofvp_network"
    environment:
      - PUID=1000
      - PGID=1000
    entrypoint:
    - "mongod"
    - "--bind_ip_all"
    - "--quiet"
    - "--logpath"
    - "/dev/null"
  ofvp_daemon_maneger:
    container_name: ofvp_daemon_maneger
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/ofvp-project/deamonmaneger:local
    depends_on:
      - ofvp_mongodb
    networks:
      - "ofvp_network"
    environment:
      NODE_ENV: "development"
      MongoDB_URL: "mongodb://ofvp_mongodb:27017"
      COOKIE_SECRET: "dev"
      PASSWORD_ENCRYPT: "dev"
    ports:
      - 3000:3000/tcp
    volumes:
      - data_api:/data