name: Publish docker image
on:
  push:
    branches:
      - main
  release:
    types:
      - released

env:
  DOCKERPLATFORM: "linux/amd64,linux/arm64"
  DOCKERIMAGE: "ghcr.io/ofvp-project/deamonmaneger"

jobs:
  publishdocker:
    runs-on: ubuntu-latest
    name: Publish Server image
    if: github.event_name == 'push' || github.event_name == 'release'
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Setup QEMU to Docker
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login into registry Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Image Build Environment
        run: |
          if [[ "${{ github.event_name }}" == 'release' ]]; then
            echo "Building release image"
            echo IMAGE_TAG=latest >> $GITHUB_ENV
          else
            echo "Building development image"
            echo IMAGE_TAG=nightly >> $GITHUB_ENV
          fi
          cat $GITHUB_ENV

      - name: Build and Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERIMAGE }}:${{ env.IMAGE_TAG }}
          platforms: ${{ env.DOCKERPLATFORM }}
          cache-from: type=gha,scope=${{ hashFiles('**/package-lock.json') }}
          cache-to: type=gha,mode=max,scope=${{ hashFiles('**/package-lock.json') }}
