name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  requests:
    runs-on: ubuntu-latest
    name: Requests
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Setup Node.JS and NPM
        uses: actions/setup-node@v3.4.0
        with:
          node-version: 16.x

      - name: Install node packages
        run: npm install

      - name: Start local MongoDB Server
        run: |
          docker run --rm --name ofvp_mongodb -d -p 27017:27017 mongo
          IP="$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ofvp_mongodb | sed "s|'||g")"
          echo "MongoDB IP: ${IP}"
          echo "MONGOIP=${IP}" >> $GITHUB_ENV

      - name: Run test
        run: npm run test
        env:
          PASSWORD_ENCRYPT: "dev"
          COOKIE_SECRET: "dev"
          MongoDB_URL: "mongodb://${{ env.MONGOIP }}:27017/test"
          NODE_ENV: "testing"