name: Test docker image
on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKERPLATFORM: "linux/amd64,linux/arm64"
  DOCKERIMAGE: "ghcr.io/ofvp-project/deamonmaneger"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Publish Server image
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Setup QEMU to Docker
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Start MongoDB And Export IP
        run: |
          docker run --rm --name ofvp_mongodb -d -p 27017:27017 mongo
          echo "mongodbip=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ofvp_mongodb | sed "s|'||g")" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ env.DOCKERIMAGE }}:local
          push: false
          load: true

      - name: Up Docker Container
        if: steps.dockertestbuild.outcome == 'success'
        run: docker run --rm --name ofvp_server -e MongoDB_URL="mongodb://${{ env.mongodbip }}:27017" -e NODE_ENV="development" -e IS_DEBUG=1 ${{ env.DOCKERIMAGE }}:local