name: Test docker image
on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKERPLATFORM: "linux/amd64,linux/arm64"
  DOCKERIMAGE: "ghcr.io/ofvp-project/deamonmaneger"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test docker image and Endpoints
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Setup QEMU to Docker
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup Node.JS and NPM
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.x

      - name: Install node packages
        run: npm install

      - name: Start MongoDB And Export IP
        run: |
          docker run --rm --name ofvp_mongodb -d -p 27017:27017 mongo
          echo "mongodbip=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ofvp_mongodb | sed "s|'||g")" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ env.DOCKERIMAGE }}:local
          push: false
          load: true

      - name: Up Docker Container
        env:
          PASSWORD_ENCRYPT: "dev" 
          COOKIE_SECRET: "dev" 
          MongoDB_URL: "mongodb://${{ env.mongodbip }}:27017" 
          NODE_ENV: "testing"
        run: |
          docker run --net=host --name=daemon_ofvp -e PASSWORD_ENCRYPT -e COOKIE_SECRET -e MongoDB_URL -e NODE_ENV ${{ env.DOCKERIMAGE }}:local &
          while true; do
            if docker logs daemon_ofvp | grep -q "3000"; then exit 0; fi
            sleep 1
          done

      - name: Run Test requests (10)
        env:
          REQUESTS: 10
        run: node test/index.js || (docker logs daemon_ofvp && exit 1)

      - name: Run Test requests (50)
        env:
          REQUESTS: 50
        run: node test/index.js || (docker logs daemon_ofvp && exit 1)

      - name: Run Test requests (500)
        env:
          REQUESTS: 500
        run: node test/index.js || (docker logs daemon_ofvp && exit 1)

      - name: Run Test requests (1000)
        env:
          REQUESTS: 1000
        run: node test/index.js || (docker logs daemon_ofvp && exit 1)