name: Test requests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  requests:
    runs-on: ubuntu-latest
    name: Requests
    strategy:
      fail-fast: false
      matrix:
        REQUETS: [10, 50, 500, 1000] 
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Setup QEMU to Docker
        uses: docker/setup-qemu-action@v1

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Start local MongoDB Server
        run: |
          docker run --rm --name ofvp_mongodb -d -p 27017:27017 mongo
          IP="$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ofvp_mongodb | sed "s|'||g")"
          echo "MongoDB IP: ${IP}"
          echo "MONGO_IP=${IP}" >> $GITHUB_ENV

      - name: Setup Node.JS and NPM
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.x

      - name: Build test image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/ofvp-project/deamonmaneger:local
          push: false
          target: server
          load: true

      - name: Up Docker Container
        env:
          PASSWORD_ENCRYPT: "dev" 
          COOKIE_SECRET: "dev" 
          MongoDB_URL: "mongodb://${{ env.MONGO_IP }}:27017/test" 
          NODE_ENV: "testing"
        run: |
          docker run --name=daemon_ofvp -d -p 3000:3000/tcp -e PASSWORD_ENCRYPT -e COOKIE_SECRET -e MongoDB_URL -e NODE_ENV ghcr.io/ofvp-project/deamonmaneger:local
          screen -dm -L -Logfile /tmp/daemon_ofvp.log docker logs --follow daemon_ofvp
          while true; do
            if cat /tmp/daemon_ofvp.log | grep -q "3000"; then
              if curl http://localhost:3000/users/v3; then
                break
              else
                echo "Cannot request users endpoint"
                exit 1
              fi
            fi
            sleep 1
          done
          IP="$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' daemon_ofvp | sed "s|'||g")"
          echo "Daemon IP: ${IP}"
          echo "DAEMON_IP=${IP}" >> $GITHUB_ENV
          exit 0

      - name: Install node packages
        run: npm install

      - name: Run Test requests (${{ matrix.REQUETS }})
        env:
          REQUESTS: ${{ matrix.REQUETS }}
          DAEMON_HOST: "http://${{ env.DAEMON_IP }}:3000"
        run: node test/index.js || (docker logs daemon_ofvp && exit 1)